repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      # - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      # - id: pretty-format-json
      - id: requirements-txt-fixer
        files: ^requirements.txt$
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pdm-project/pdm
    rev: 2.1.1
    hooks:
      - id: pdm-export
        args: ["--pyproject", "--without-hashes", "--prod", "-G:all", "-o", "requirements.txt"]
        files: ^pyproject.toml$

default_language_version:
    python: python3.10
